# Generated by Django 4.1.6 on 2023-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_product_is_published_product_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_release',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
