# Generated by Django 4.1.6 on 2023-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_product_date_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='large_description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
