# Generated by Django 4.1.6 on 2023-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_product_large_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_release',
            field=models.IntegerField(null=True),
        ),
    ]
